"""empty message

Revision ID: a1f73ba61928
Revises: 
Create Date: 2019-05-17 23:30:37.939445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f73ba61928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Countries',
    sa.Column('COUNTRY_ID', sa.Integer(), nullable=False),
    sa.Column('COUNTRY_ISO_CODE', sa.Integer(), nullable=True),
    sa.Column('COUNTRY_NAME', sa.VARCHAR(length=100), nullable=True),
    sa.Column('COUNTRY_STATE_NAME', sa.VARCHAR(length=150), nullable=True),
    sa.Column('COUNTRY_PHONE_CODE', sa.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('COUNTRY_ID')
    )
    op.create_table('Applicants',
    sa.Column('APPL_ID', sa.Integer(), nullable=False),
    sa.Column('APPL_CREATED', sa.DateTime(), nullable=True),
    sa.Column('APPL_FIRST_NAME', sa.VARCHAR(length=50), nullable=True),
    sa.Column('APPL_MIDDLE_NAME', sa.VARCHAR(length=50), nullable=True),
    sa.Column('APPL_LAST_NAME', sa.VARCHAR(length=100), nullable=True),
    sa.Column('APPL_FATHER_NAME', sa.VARCHAR(length=50), nullable=True),
    sa.Column('APPL_GENDER', sa.CHAR(length=1), nullable=True),
    sa.Column('APPL_DATE_OF_BIRTH', sa.DATE(), nullable=True),
    sa.Column('APPL_PHONE_NUM', sa.VARCHAR(length=10), nullable=True),
    sa.Column('APPL_EMAIL', sa.VARCHAR(length=100), nullable=True),
    sa.Column('APPL_CITY', sa.VARCHAR(length=100), nullable=True),
    sa.Column('COUNTRY_ID', sa.Integer(), nullable=True),
    sa.Column('APPL_USERNAME', sa.VARCHAR(length=100), nullable=True),
    sa.Column('APPL_PASSWORD', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['COUNTRY_ID'], ['Countries.COUNTRY_ID'], ),
    sa.PrimaryKeyConstraint('APPL_ID'),
    sa.CheckConstraint('"APPL_GENDER" IN (\'M\',\'F\')')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Applicants')
    op.drop_table('Countries')
    # ### end Alembic commands ###
